version: "3.8"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "7432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: postgres
      PHP_PG_ADMIN_SERVER_SSL_MODE: disable
    ports:
      - "8080:80"
    depends_on:
      - postgres

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
